*** Settings ***
Documentation    This is RobotFrame work script
Library    Selenium2Library
# Library    AutoItLibrary
Library    OperatingSystem
Library    DateTime  
Library    Collections
Library    Screenshot
Library    String
Library    Process
Resource   locators_Acumos.robot
Resource   resource_Acumos_data.robot
        
*** Test Cases *** 
Launch Browser
   Setup Browser    
Header Validation
   Verify header  
Discover Acumos Section
  Verify Discover Acumos Section   
Verify SignUp Functionality
  To Verify SignUp Functionality 
To Verify Login With Invalid Username and Password
  Verify Login With Invalid Username and Password
To Verify SignUp for Invalid Inputs for Username and Email
  Verify SignUp for Invalid Inputs for Username and Email 
Login Portal
  Verify Login              
Marketplace Tab Verification  
  Verify Marketplace Tab
My Models Tab Verification
  Verify My Models tab  
To verify catalog menu is visible for publisher role(catalog tab)
  Verify catalog menu is visible for publisher role
Onboarding model tab Verification
  Verify Onboarding model tab    
Design Studio Tab Verification  
  Verify Design Studio Tab
Site Admin Tab Verification  
  Verify Site Admin Tab
Publish request tab verification
  Verify Publish Request tab  
To verify data is sorting in ascending or descending order when user click on icons
  Verify data is sorting in ascending or descending order when user click on icons
To verify catalog and access level column added in publish request screen																								
  Verify catalog and access level column added in publish request screen
Verify previous is disabled when page load and when page end next is disabled
  To verify previous is disabled when page load and when page end next is disabled
  
To verify ellipsis click functionality
  To verify ellipsis click functionality
  
Account Settings Page Navigation    
  Verify Navigation to Account Settings Page                              
Verify delete hyperlink is displaying on account setting screen
  To verify delete hyperlink is displaying on account setting screen 
Verify API token is deleted by click on the delete token hyperlink
  To verify API token is deleted by click on the delete token hyperlink 
Verify API token is regenerated by click on the Refresh hyperlink after deletion
  To verify API token is regenerated by click on the Refresh hyperlink after deletion	
To verify select favorite catalogs option is displaying in account settings page
  Verify select favorite catalogs option is displaying in account settings page  
To verify content of select favorite catalog screen
  Verify content of select favorite catalog screen 
To verify catalog description is displaying on the search box when user clicks on the icon																													   
   Verify catalog description is displaying on the search box when user clicks on the icon	
Verify making favorite catalog functionality	
   To verify making favorite catalog functionality
Verify Check box is displaying on notification screen to select all notification
  To verify Check box is displaying on notification screen to select all notification
Manage My Model Management Options
  Verify Manage My Model Management Options
To verify View On-Boarding history tab is present in On-Boarding model page
  Verify view On-Boarding history tab is present in On-Boarding model page
To verify On-Boarding history is displayed on clicking View On-Boarding history tab
  Verify On-Boarding history is displayed on clicking View On-Boarding history tab
To verify functionalities of view on-boarding history page
  Verify functionalities of view on-boarding history page  
To verify search functionality for a valid user for On-Boarding	
  Verify search functionality for On-Boarding  
To verify the status is showing while model on-boarding is in process
  Verify the status is showing while model on-boarding is in process 
To verify the detailed on-boarding failure information is shown on click of view results
  Verify the detailed on-boarding failure information is shown on click of view results 
To verify federation admin screen show number of subscription records	                                                                                                                   
  Verify federation admin screen show number of subscription records 
To verify view/add link in subscriptions column
  Verify view/add link in subscriptions column 
To verify drop down values and view/add pop-up appears on click of view/add link																													   
  Verify view/add pop-up appears on click of view/add link
To verify delete icon is displaying on the error model(not in deleted section)
  Verify delete icon is displaying on the error model(not in deleted section)
To verify error detail popup is open on click of error model
  Verify error detail popup is open on click of error model
To verify delete is working for error model
  Verify delete is working for error model
Search in My Models Page
  Verify Search Functionality 
To verify filter by category functionality
  Verify filter by category functionality
To verify content on catalog screen
  Verify content on catalog screen
To verify catalog detail is displaying when user selects a value from the drop down
  Verify catalog detail is displaying when user selects a value from the drop down  
To verify edit catalog functionality
  Verify edit catalog functionality  
To verify delete catalog functionality																													   
  Verify delete catalog functionality 
   
To verify "Peer access" icon display under action section on catalog page
   Verify "Peer access" icon display under action section on catalog page
To verify "Grant peer access" button display on manage peer(s)Access page
   Verify "Grant peer access" button display on manage peer(s)Access page
To verify that user will click on (X) icon or cancel button from grant peer access pop-up
   Verify that user will click on (X) icon or cancel button from grant peer access pop-up
To verify that user will click on "Grant Access" button from grant peer access pop-up without selecting any peer   
   Verify that user will click on "Grant Access" button from grant peer access pop-up without selecting any peer
To verify that user will click on "Grant Access" button from grant peer access pop-up
   Verify that user will click on "Grant Access" button from grant peer access pop-up
To verify that user will click on "Remove button" from manage peer(s) access page
   Verify that user will click on "Remove button" from manage peer(s) access page
To verify that user will click on (X) icon from manage peer(s) access page
   Verify that user will click on (X) icon from manage peer(s) access page
 
To verify error message is displaying when no author is added and user tries to publish the model
   Verify error message is displaying when no author is added and user tries to publish the model
Model Details page Tabs
  Verify Model Details page Tabs
To Verify Solution ID is displaying on Model Details Page
  Verify Solution ID is displaying on Model Details Page
To Verify Solution ID is displaying on Manage My Model Page
  Verify Solution ID is displaying on Manage My Model Page      
Model Delete In My Models For Unpublished Model    
  Verify Delete Model In MyModels For Unpublished Model   
To Check Status Of Unpublished Solution in Model Details page
  Verify the Status of Unpublished solution in Model details page 
Dashboard options in Site Admin
  Verify dashboard options in Site Admin         
To Check Status Of Deleted Solution in Model Details page
  Verify the Status of Deleted solution in Model details page
To Verify that Manage My Model Button for Deleted solution is disabled     
  Verify that Manage My Model Button for Deleted solution is disabled 
To Verify Adding Author Tab Is Present In Manage My Models Page
  Verify Adding Author Tab Is Present In Manage My Models Page        
Adding New Author In Manage My Models Page
  Verify Adding New Author In Manage My Models Page
To verify catalog drop down and select favorite catalog button is displaying on marketplace screen
  Verify catalog drop down and select favorite catalog button is displaying on marketplace screen
To verify select favorite catalogs functionality
  Verify select favorite catalogs functionality
  
To verify whether role management tab is present in dashboard options  
  Verify whether role management tab is present in dashboard options
To verify whether role management tab is clickable
  Verify whether role management tab is clickable
To verify components in role management tab
  Verify components in role management tab
To verify whether sorting is working for role management options
  Verify whether sorting is working for role management options
To verify whether create new role button is present in role management page
  Verify whether create new role button is present in role management page
To verify create new role functionality
  Verify create new role functionality
To verify whether new role is visible in role management page after creating it
  Verify whether new role is visible in role management page after creating it
To verify update role functionality
  Verify update role functionality
To verify delete role functionality
  Verify delete role functionality
  
To verify unpublish tab is present for published models
  Verify unpublish tab is present for published models
To verify the unpublish model functionality
  Verify the unpublish model functionality
To verify that the unpublish model pop-up should be visible after clicking unpublish model button on manage my models page
  Verify that the unpublish model pop-up should be visible after clicking unpublish model button on manage my models page
To verify unpublish tab is not present for unpublished models
  Verify unpublish tab is not present for unpublished models    
Publish Solution in Marketplace
  Verify To Publish Solution In Marketplace
To verify catalog name is displaying on the tiles (Marketplace...in models)
  Verify catalog name is displaying on the tiles
To verify Already Publish Solution In Published To Marketplace
  Verify The Published Solution In Published To Marketplace
To Verify the description available in published in marketplace model
  Verify the description available in published in marketplace model 
To verify long comment is displaying on click of view
  Verify long comment is displaying on click of view             
To verify complete model name display in the rate section on model description screen
  Verify complete model name display in the rate section on model description screen    
To Verify signature is displaying on model description screen for composite solution
  Verify signature is displaying on model description screen for composite solution     
To verify category is displaying for model except unpublished status
  Verify category is displaying for model except unpublished status  
Model Delete In My Models For Published Model    
  Verify Delete Model In MyModels For Published Model   
Add New User In User Management and User Activation        
  Verify adding new user in User Management and User Activation          
Logout Portal
  Verify Logout     
Verify Add User By Login With Newly Added User    
  Verify Add User By Login With Newly Added User
To Verify Change Password On Account Setting Page
  Verify Change Password On Account Setting Page     
Tear Down browser
  Tear Down
 

 
*** Keywords ***
Setup Browser    #Launch web browser  i.e Firefox
	 Open Browser    ${URL}   ${BROWSER}       ff_profile_dir=${FF_PROFILE}
	 Maximize Browser Window
	 Set Selenium Speed    2s 
	 Check Header Status  #do not commit in gerrit
 
 
Check Header Status     #do not commit in gerrit
	 ${status_header}  ${result}=    Run keyword and ignore error    Element Should Be Visible      ${homeLink}   30s  #${acumos_logo_without_login}
	 Run Keyword If      "${status_header}" == "FAIL"     Refresh Page    
 
 Refresh Page    #do not commit in gerrit
	  Reload Page
	  sleep  5s
	  Check Header Status
 
 
 Verify header       
	  Wait Until Element Is Visible    ${homeLink}  10s 
	  Wait Until Element Is Visible    ${marketplaceLink}    10s   
	  Wait Until Element Is Visible    ${modelerResorcesLink}    10s

Verify Discover Acumos Section    
	  Wait Until Element Is Visible    ${homeLink}  10s 
	  Wait Until Keyword Succeeds  120   10    Wait Until Element Is Visible    ${discover_Marketplace}    30s     
	  Wait Until Element Is Visible    ${discover_DesignStudio}    10s
	  Wait Until Element Is Visible    ${discover_SDN_ONAP}    10s 
	  Wait Until Element Is Visible    ${discover_TeamUp}    10s
	  Wait Until Element Is Visible    ${discover_Onboarding}    10s         
        
To Verify SignUp Functionality
     sleep    10s
	 Open Browser    ${URL}   ${BROWSER}       ff_profile_dir=${FF_PROFILE}
	 Maximize Browser Window
	 Set Selenium Speed    2s
	 sleep  3s
	 ${signUp_Data} =   Get Current Date    result_format=%d_%m_%Y_%H_%M_%S
	 Set Suite Variable    ${signUp_Data}
	 Wait Until Element Is Visible    ${signUpLink}    15s    
	 Click Element    ${signUpLink}
	 Wait Until Element Is Visible    ${firstNameInputbox}    15s
	 Input Text    ${firstNameInputbox}    ${signUp_Data}
	 Wait Until Element Is Visible    ${lastNameInputbox}    15s
	 Input Text    ${lastNameInputbox}    ${signUp_Data}
	 Wait Until Element Is Visible    ${signUpUserName}    15s
	 Input Text    ${signUpUserName}    ${signUp_Data}
	 Wait Until Element Is Visible    ${signUpEmailId}    15s
	 Input Text    ${signUpEmailId}    ${signUp_Data}@test.com
	 Wait Until Element Is Visible    ${signUpPassword}      15s
	 Input Text    ${signUpPassword}     SignUpTest@1234
	 Wait Until Element Is Visible    ${signUpConfirmPassword}      15s
	 Input Text    ${signUpConfirmPassword}     SignUpTest@1234
	 Click Element    //div[@class='signup-txt-mob']/label[contains(text(),'Already')]
	 Wait Until Element Is Enabled    ${signUpBtn}    20s
	 Element Should Be Enabled    ${signUpBtn}
	 Set Focus To Element    ${signUpBtn}
	 Click Element    ${signUpBtn}
	 sleep    30s
	 Wait Until Element Is Visible    ${signInLink}     20s
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    10s
	 Click Element        ${signInLink}
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   25s   
	 Input Text    ${loginEmailAddressEntry}    ${username} 
	 Wait Until Element Is Visible    ${loginPassword}    25s
	 Input Text    ${loginPassword}    ${password}
	 Click Button    ${signInButton}   
	 Wait Until Element Is Visible    ${siteAdminIcon}         25s
	 Click Element    ${siteAdminIcon}
	 Wait Until Element Is Visible    ${user_Management_Tab}    15s
	 Click Element    ${user_Management_Tab}
	 Wait Until Element Is Visible    ${searchUser_UserManagement}    15s
	 Input Text    ${searchUser_UserManagement}    ${signUp_Data}@test.com
	 Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_uname}    ${signUp_Data}
	 Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_email}    ${signUp_Data}@test.com
	 Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_role_MLPSysUser}    MLP System User
	 Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_status}    Pending
	 Click Element    ${AddedUser_FirstChkBox}
	 Click Element    ${bulkActionsDrpDwn}
	 Wait Until Element Is Visible    ${bulkAction_ActiveUserOption}    5s
	 Click Element    ${bulkAction_ActiveUserOption}
	 Click Element    ${UserMgmt_ApplyBtn}
	 Wait Until Element Is Visible    ${confirmBtn_ActiveUserPopup}    15s
	 Click Element    ${confirmBtn_ActiveUserPopup}
	 Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_status}    Active
	 Wait Until Element Is Visible    ${signOut}      10s        
	 Click Element        ${signOut}    
	 Wait Until Keyword Succeeds     60     5    Wait Until Element Is Visible    ${signInLink}   30s
	 Wait Until Keyword Succeeds     60     5    Element Should Be Visible    ${signInLink}
	 sleep    5s
	 Click link        ${signInLink}
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   60s       
	 Input Text    ${loginEmailAddressEntry}      ${signUp_Data}@test.com 
	 Wait Until Element Is Visible    ${loginPassword}    25s
	 Input Text    ${loginPassword}    SignUpTest@1234
	 Click Button    ${signInButton}
	 Wait Until Element Is Visible    ${loginAccountInfo}    25s
	 Element Should Be Visible    ${loginAccountInfo} 
	  # Close Browser 
	 Wait Until Element Is Visible    ${signOut}      10s        
	 Click Element        ${signOut} 
 
Verify Login With Invalid Username and Password
      sleep    10s
	  # Open Browser    ${URL}   ${BROWSER}       ff_profile_dir=${FF_PROFILE}
	  # Set Selenium Speed    1s
	 Wait Until Element Is Visible    ${signInLink}     30s
	 Click Element        ${signInLink}
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   25s   
	 Input Text    ${loginEmailAddressEntry}    InvalidUserTest     
	 Wait Until Element Is Visible    ${loginPassword}    25s
	 Input Text    ${loginPassword}    InvalidPasswordTest
	 Click Button    ${signInButton}
	 Wait Until Element Is Visible    ${loginUserNotExistError}   20s
	 Wait Until Element Is Visible    ${closeSignIn}      15s
	 Click Element    ${closeSignIn}
	  # Close Browser                           
 
Verify SignUp for Invalid Inputs for Username and Email
     sleep    10S
	  # Open Browser    ${URL}   ${BROWSER}       ff_profile_dir=${FF_PROFILE}
	  # Set Selenium Speed    1s
	  # sleep  3s
	 Wait Until Element Is Visible    ${signUpLink}    20s    
	 Click Element    ${signUpLink}
	 Wait Until Element Is Visible    ${firstNameInputbox}    15s
	 Input Text    ${firstNameInputbox}    TestFN
	 Wait Until Element Is Visible    ${lastNameInputbox}    15s
	 Input Text    ${lastNameInputbox}    TestLN
	 Wait Until Element Is Visible    ${signUpUserName}    15s
	 Click Element    ${signUpUserName}  
	 Wait Until Element Is Visible    ${signUpEmailId}    15s
	 Input Text    ${signUpEmailId}    testEmail
	 Wait Until Element Is Visible    ${signUpPassword}      15s
	 Click Element    ${signUpPassword}
	 Wait Until Element Is Visible    ${usernameError}    15s    
	 Wait Until Element Is Visible    ${emailError}    15s
	 sleep    15s
	 Wait Until Element Is Visible    ${closeSignUp}      15s
	 Click Element    ${closeSignUp}
	  # Close Browser 
	  
 Verify Login 
     Wait Until Element Is Visible    ${homeLink}     30s
     sleep    15s      
	 Click Link        ${homeLink}
	 Wait Until Element Is Visible    ${signInLink}     30s
	 Click Element        ${signInLink}
	  #sleep  15s
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   30s   
	 Input Text    ${loginEmailAddressEntry}    ${username} 
	  #sleep  15s 
	 Wait Until Element Is Visible    ${loginPassword}    10s
	 Input Text    ${loginPassword}    ${password}
	 Click Button    ${signInButton}
	 sleep    10s
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Visible    ${loginAccountInfo}    30s
	  # Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${loginAccountInfo}    10s
	 Element Should Be Visible    ${loginAccountInfo}
	 ${status_interestPopup}  ${result}=    Run keyword and ignore error    Wait Until Element Is Visible      ${interestPopup_closeBtn}    30s
	 Run Keyword If      "${status_interestPopup}" == "PASS"     Click Element    ${interestPopup_closeBtn} 
   
Verify Marketplace Tab       
	 Wait Until Element Is Visible    ${marketPlaceIcon}    10s    
	 Click Element    ${marketPlaceIcon}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s       
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${marketPlacePageTitle}  10s    
	 Element Should Be Visible    ${marketPlacePageTitle}
	  
              
Verify My Models Tab        
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Double Click Element    ${myModelIcon}                            
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible     ${myModelPageTitle}  10s    
	 Element Should Contain    ${myModelPageTitle}     My Models

Verify catalog menu is visible for publisher role
    Wait Until Element Is Visible    ${catalogIcon}    10s
	Element Should Be Visible    ${catalogIcon}
    Click Element    ${catalogIcon}
    Wait Until Element Is Visible    ${catalogIconTitle}    10s
    Element Should Be Visible    ${catalogIconTitle}

Verify Onboarding model tab
     Wait Until Element Is Visible    ${OnboardingModelIcon}   10s
	 Click Element    ${OnboardingModelIcon}
	 Wait Until Element Is Visible    ${OnboardingModelTitle}   10s
	 Element Should Be Visible    ${OnboardingModelTitle}
 
                  
Verify Design Studio Tab   
	 Wait Until Element Is Visible    ${designStudioIcon}   10s
	 Click Element    ${designStudioIcon}
	 Wait Until Element Is Visible    ${designStudioTitle}   10s
	 Element Should Be Visible    ${designStudioTitle}
	        
Verify Site Admin Tab       
	 Wait Until Element Is Visible    ${siteAdminIcon}   10s
	 Click Element    ${siteAdminIcon}
	 Wait Until Element Is Visible    ${siteAdminPageTitle}   10s    
	 Element Should Be Visible    ${siteAdminPageTitle}

Verify Publish Request tab
	 Wait Until Element Is Visible    ${publishRequestIcon}   10s
	 Click Element    ${publishRequestIcon}
	 Wait Until Element Is Visible    ${publishRequestPageTitle}   10s    
	 Element Should Be Visible    ${publishRequestPageTitle}     
     
Verify data is sorting in ascending or descending order when user click on icons
	 Wait Until Element Is Visible    ${Model_Name}    10s
	 Element Should Be Visible   ${Model_Name}
	 Click Element    ${Model_Name}
	 Wait Until Element Is Visible    ${Version}    10s
	 Element Should Be Visible   ${Version}
	 Click Element    ${Version}
	 Wait Until Element Is Visible    ${Requester}    10s
	 Element Should Be Visible   ${Requester}
	 Click Element    ${Requester}
	 Wait Until Element Is Visible    ${Created_Date}    10s
	 Element Should Be Visible   ${Created_Date}
	 Click Element    ${Created_Date}
	 Wait Until Element Is Visible    ${Catalog}    10s
	 Element Should Be Visible   ${Catalog}
	 Click Element    ${Catalog}
	 Wait Until Element Is Visible    ${Access_Level_PR}    10s
	 Element Should Be Visible   ${Access_Level_PR}
	 Click Element    ${Access_Level_PR}
	 Wait Until Element Is Visible    ${Request_Status}    10s
	 Element Should Be Visible   ${Request_Status}
	  # Click Element    ${Request_Status}
	 Wait Until Element Is Visible    ${Comments}    10s
	 Element Should Be Visible   ${Comments}
	  # Click Element    ${Comments}

Verify catalog and access level column added in publish request screen
    Wait Until Element Is Visible    ${homeIcon}   30s
	Click Element    ${homeIcon}
	Wait Until Element Is Visible    ${publishRequestIcon}   30s
	Click Element    ${publishRequestIcon}
	Wait Until Element Is Visible    ${Catalog}    10s
	Element Should Be Visible    ${Catalog}
	Wait Until Element Is Visible    ${Access_Level_PR}    10s
	Element Should Be Visible    ${Access_Level_PR}

To verify previous is disabled when page load and when page end next is disabled
     Wait Until Element Is Visible    ${homeIcon}    10s
     Click Element    ${homeIcon}  
     Wait Until Element Is Visible    ${marketPlaceIcon}    10s
     Click Link	${marketPlaceIcon} 
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
     sleep    10s 
     Execute JavaScript    window.scrollTo(0,200)
     Wait Until Element Is Visible    ${Page_1_Btn}    10s
     Element Should Be Visible    ${Page_1_Btn}
     Wait Until Element Is Visible    ${PreviousBtn}    10s
     Element Should Be Visible    ${PreviousBtn} 

To verify ellipsis click functionality     
     Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
     Wait Until Element Is Visible    ${ellipsisBtn}    10s
     Element Should Be Visible    ${ellipsisBtn}
     Click Button    ${ellipsisBtn}
     Wait Until Element Is Visible    ${nextBtn}    10s
     Element Should Be Visible    ${nextBtn}
     Click Button    ${nextBtn}
     
Verify Navigation to Account Settings Page
	 Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}
	 Wait Until Element Is Visible    ${accountInfo_Dropdown}    10s
	 Click Element    ${accountInfo_Dropdown}
	 sleep    10s
	 Click Link    ${accountSetting_link}
	 Wait Until Element Is Visible    ${accountSetting_PageTitle}    20s   
	 Element Should Be Visible    ${accountSetting_PageTitle} 
	  # Input Text	${1stName}	Hakuna
     # Input Text	${2ndName}	Matata
     # Wait Until Element Is Enabled	${UpdateAccount}    5s
     # Click Element	${UpdateAccount}
     # Wait Until Element Is Visible	${loginAccountInfo}    5s
     # Click Element	${signOut}
     # Wait Until Element Is Visible	${signInLink}    30s
     # Click Element	${signInLink}
     # Wait Until Element Is Visible    ${loginEmailAddressEntry}   30s   
     # Input Text    ${loginEmailAddressEntry}    ${username} 
     # Wait Until Element Is Visible    ${loginPassword}    10s
     # Input Text    ${loginPassword}    ${password}
     # Click Button    ${signInButton}
     # sleep    10s
     # Wait Until Keyword Succeeds  60    5    Wait Until Element Is Visible    ${loginAccountInfo}    30s
     # Element Should Be Visible    ${loginAccountInfo}
     # ${status_interestPopup}  ${result}=    Run keyword and ignore error    Wait Until Element Is Visible      ${interestPopup_closeBtn}    30s
     # Run Keyword If      "${status_interestPopup}" == "PASS"     Click Element    ${interestPopup_closeBtn}
	      
  
To verify delete hyperlink is displaying on account setting screen
     Wait Until Element Is Visible    ${deleteApiToken}    10s
     Element Should Be Visible    ${deleteApiToken}
     
To verify API token is deleted by click on the delete token hyperlink
     sleep    10s
     Click Element    ${deleteApiToken}
     Wait Until Element Is Visible    ${API_tokenTextarea}    15s
     Element Should Be Visible    ${API_tokenTextarea} 

To verify API token is regenerated by click on the Refresh hyperlink after deletion 
     Wait Until Element Is Visible    ${Refresh_Token}    15s
     Element Should Be Visible    ${Refresh_Token} 
     Click Element    ${Refresh_Token}
     Wait Until Element Is Visible    ${API_tokenTextarea}    15s
     Element Should Be Visible    ${API_tokenTextarea} 
     
Verify select favorite catalogs option is displaying in account settings page
    sleep    10s
    Wait Until Element Is Visible    ${SelectFavorite_Catalogs}    10s
	Element Should Be Visible    ${SelectFavorite_Catalogs}
	Click Element	${SelectFavorite_Catalogs}

Verify content of select favorite catalog screen
    Wait Until Element Is Visible    ${SelectCatalogs_SearchBox}   30s
	Click Element    ${SelectCatalogs_SearchBox}
	Input Text    ${SelectCatalogs_SearchBox}    TESTING_CATALOG
	Wait Until Element Is Visible    ${SelectedModel_Catalog}    10s
	Element Should Be Visible    ${SelectedModel_Catalog}       	      

Verify catalog description is displaying on the search box when user clicks on the icon
     Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link    ${homeIcon}
	 Wait Until Element Is Visible    ${accountInfo_Dropdown}    10s
	 Click Element    ${accountInfo_Dropdown}
	 Wait Until Element Is Visible    ${accountSetting_link}    10s
	 Click Link    ${accountSetting_link}
	 Wait Until Element Is Visible    ${accountSetting_PageTitle}    20s   
	 Element Should Be Visible    ${accountSetting_PageTitle}  
	 Wait Until Element Is Visible    ${SelectFavorite_Catalogs}    10s
	 Element Should Be Visible    ${SelectFavorite_Catalogs}
	 Click Element    ${SelectFavorite_Catalogs}
	 Wait Until Element Is Visible    ${SelectCatalogs_SearchBox}    10s
	 Element Should Be Visible    ${SelectCatalogs_SearchBox}
	 Click Element    ${SelectCatalogs_SearchBox}
	 Input Text    ${SelectCatalogs_SearchBox}    MY PUBLIC MODELS-IST2    
	 Wait Until Element Is Visible    ${MY PUBLIC MODELS_IST2}    10s
	 Element Should Be Visible    ${MY PUBLIC MODELS_IST2}

To verify Check box is displaying on notification screen to select all notification
     Wait Until Element Is Visible    ${homeIcon}    10s
     Click Element    ${homeIcon}
     Wait Until Keyword Succeeds    60    5    Wait Until Element Is Visible    ${notification_link}   30s
     sleep    10s
     Element Should Be Visible    ${notification_link}
     Click Element    ${notification_link}
     Wait Until Element Is Visible    ${readAllMessages}    10s
     Element Should Be Visible    ${readAllMessages}
     Click Element    ${readAllMessages}
     Wait Until Element Is Visible    ${manage_notifications_title}    10s
     Element Should Be Visible    ${manage_notifications_title}
     Wait Until Element Is Visible    ${subject_link}    10s
     Element Should Be Visible    ${subject_link}
     Wait Until Element Is Visible    ${selectAll_checkbox}    10s
     Click Element    ${selectAll_checkbox}
     
To verify making favorite catalog functionality	
     
	 Wait Until Element Is Visible    ${FavoriteCatalog_Symbol}   30s
	 Click Element    ${FavoriteCatalog_Symbol} 
	 Element Should Be Visible    ${FavoriteCatalog_Symbol}
	 sleep    5s
	 Click Element    ${FavoriteCatalog_Symbol}

Verify Adding Author Tab Is Present In Manage My Models Page
     Wait Until Element Is Visible    ${homeIcon}   10s
	 Element Should Be Visible	${homeIcon}
	 Click Element	${homeIcon}
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   5    Element Text Should Be     ${imageToVerify}     ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   5    Wait Until Element Is Visible    ${check_Image_loaded}     30s
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    15s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${manageAuthors}    20s
	 Element Should Be Visible     ${manageAuthors}    
 
Verify Adding New Author In Manage My Models Page 
     Click Element    ${manageAuthors}
     Wait Until Element Is Visible    ${publisherName_Authors}    10s
	 Input Text    ${publisherName_Authors}     AcumosAdmin 
	 Wait Until Element Is Enabled    ${SaveBtn}    15s
	 Element Should Be Enabled    ${SaveBtn}
	 Click Element    ${SaveBtn}   
	 Wait Until Element Is Visible    ${authorName}    10s
	 Input Text    ${authorName}     Test
	 Input Text    ${authorContactInfo}    Test
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Wait Until Element Is Enabled    ${addAuthorBtn}    15s
	 Element Should Be Enabled    ${addAuthorBtn}    
	 Click Element    ${addAuthorBtn}

Verify catalog drop down and select favorite catalog button is displaying on marketplace screen
    Wait Until Element Is Visible    ${homeIcon}    10s
    Click Element    ${homeIcon}
	Wait Until Element Is Visible    ${marketPlaceIcon}    10s
	Click Element    ${marketPlaceIcon} 
	Wait Until Element Is Visible	${All_Catalogs}	10s
	Element Should Be Visible	${All_Catalogs}	
	Wait Until Element Is Visible	${Select_Favorite_Catalogs_Tab}	10s
	Element Should Be Visible	${Select_Favorite_Catalogs_Tab}	 

Verify select favorite catalogs functionality
    sleep    5s
    Wait Until Element Is Visible	${Select_Favorite_Catalogs_Tab}	10s
	Click Element	${Select_Favorite_Catalogs_Tab}  
	Wait Until Element Is Visible    ${SelectFavorite_Catalogs}    10s
	Element Should Be Visible    ${SelectFavorite_Catalogs} 

Verify Manage My Model Management Options
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}    30s
	 Wait Until Element Is Visible    ${check_Image_loaded}    30s    
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   5  Element Text Should Be     ${imageToVerify}    ${SearchModelName_MyModel}
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${onboardingTab_ManageMyModel}    10s    
	 Element Should Be Visible   ${onboardingTab_ManageMyModel}
	 Wait Until Element Is Visible    ${shareWithTeamTab}    10s
	 Element Should Be Visible   ${shareWithTeamTab}
	 Wait Until Element Is Visible    ${manageAuthors}    10s
	 Element Should Be Visible   ${manageAuthors}
	 Wait Until Element Is Visible    ${publishToMarketplaceTab}    10s
	 Element Should Be Visible   ${publishToMarketplaceTab}
	 Wait Until Element Is Visible    ${Export_DeployToCloud}    10s
	 Element Should Be Visible   ${Export_DeployToCloud}
	 Wait Until Element Is Visible    ${viewDownloadsTab}    10s
	 Element Should Be Visible   ${viewDownloadsTab}
	 Wait Until Element Is Visible    ${replyToCommentsTab}    10s
	 Element Should Be Visible   ${replyToCommentsTab}	 

Verify View On-Boarding history tab is present in On-Boarding model page
    Wait Until Element Is Visible    ${homeIcon}    10s
    Click Element    ${homeIcon}
	Wait Until Element Is Visible    ${OnboardingModelIcon}    10s
    Click Element    ${OnboardingModelIcon}
	Wait Until Element Is Visible    ${OnboardingModelTitle}   10s
	Element Should Be Visible    ${OnboardingModelTitle}
	Wait Until Element Is Visible    ${OnboardingHistoryTab}   10s
	Element Should Be Visible    ${OnboardingHistoryTab}
	
Verify On-Boarding history is displayed on clicking View On-Boarding history tab
    Click Element	${OnboardingHistoryTab}
	Wait Until Element Is Visible    ${OnboardingHistoryTab_title}   10s
	Element Should Be Visible    ${OnboardingHistoryTab_title}
	
Verify functionalities of view on-boarding history page	
    Wait Until Element Is Visible    ${Model_Name_OB}   10s
	Element Should Be Visible    ${Model_Name_OB}
	Wait Until Element Is Visible    ${Status_Code}   10s
	Element Should Be Visible    ${Status_Code}
    Wait Until Element Is Visible    ${Solution_Id}   10s
	Element Should Be Visible    ${Solution_Id}
	Wait Until Element Is Visible    ${Revision_Id}   10s
	Element Should Be Visible    ${Revision_Id}
    Wait Until Element Is Visible    ${Date_Time}   10s
	Element Should Be Visible    ${Date_Time}
	Wait Until Element Is Visible    ${Status_OB}   10s
	Element Should Be Visible    ${Status_OB}
    Wait Until Element Is Visible    ${Action}   10s
	Element Should Be Visible    ${Action}
	Wait Until Element Is Visible    ${In_Progress}   10s
	Element Should Be Visible    ${In_Progress}
	Click Element	${In_Progress}
    Wait Until Element Is Visible    ${Fail}   10s
	Element Should Be Visible    ${Fail}
	Click Element	${Fail}
    Wait Until Element Is Visible    ${Successful}   10s
	Element Should Be Visible    ${Successful}
	Click Element	${Successful}
	
Verify search functionality for On-Boarding
    Wait Until Element Is Visible    ${All}   10s
	Element Should Be Visible    ${All}
	Click Element	${All}
    Wait Until Keyword Succeeds    60    5    Wait Until Element Is Visible    ${searchModelTxtbox_Onboarding}   30s
    Element Should Be Visible	${searchModelTxtbox_Onboarding}
	Click Element    ${searchModelTxtbox_Onboarding}
	Input Text    ${searchModelTxtbox_Onboarding}    ${SearchModelName_Public}
	Wait Until Element Is Visible    ${ModelName_MS}   15s
	Element Should Be Visible	${ModelName_MS}
		
Verify the status is showing while model on-boarding is in process
    # Wait Until Element Is Visible    ${success_status}   10s
	# Element Should Be Visible	${success_status}
	# Wait Until Element Is Visible    ${homeIcon}    10s
    # Click Element    ${homeIcon}
	# Wait Until Element Is Visible    ${OnboardingModelIcon}    10s
    # Click Element    ${OnboardingModelIcon}
	# Wait Until Element Is Visible    ${OnboardingModelTitle}   10s
	# Element Should Be Visible    ${OnboardingModelTitle}
	# Wait Until Element Is Visible    ${OnboardingHistoryTab}   10s
	# Element Should Be Visible    ${OnboardingHistoryTab}
	# Click Element	${OnboardingHistoryTab}
	# Wait Until Element Is Visible    ${OnboardingHistoryTab_title}   10s
	# Element Should Be Visible    ${OnboardingHistoryTab_title}
	# Wait Until Element Is Visible    ${searchModelTxtbox_Onboarding}   30s
	# Click Element    ${searchModelTxtbox_Onboarding}
	Clear Element Text    ${searchModelTxtbox_Onboarding}         
	Input Text    ${searchModelTxtbox_Onboarding}    ${SearchModelName_Error}
	Wait Until Element Is Visible    ${Fail_status}   15s
	Element Should Be Visible	${Fail_status}
	
Verify the detailed on-boarding failure information is shown on click of view results
    Wait Until Element Is Visible    ${View_Results}   15s
	Element Should Be Visible	${View_Results}
	Click Element	${View_Results}
	Wait Until Element Is Visible    ${Error-Pop-up}   15s
	Element Should Be Visible	${Error-Pop-up}
	Wait Until Element Is Visible   ${Error-Pop-up_OK}   15s
	Element Should Be Visible	${Error-Pop-up_OK}
	Click Element	${Error-Pop-up_OK}		
	      
Verify federation admin screen show number of subscription records
    Wait Until Element Is Visible    ${homeIcon}   10s
	Element Should Be Visible	${homeIcon}
	Click Element	${homeIcon}
	Wait Until Element Is Visible    ${siteAdminIcon}   10s
	Element Should Be Visible	${siteAdminIcon}
	Click Element	${siteAdminIcon}
	Wait Until Element Is Visible    ${siteAdminPageTitle}   10s
	Element Should Be Visible	${siteAdminPageTitle}
	Wait Until Element Is Visible    ${federation_Tab}   10s
	Element Should Be Visible	${federation_Tab}
	Click Element	${federation_Tab}
	Wait Until Element Is Visible    ${federation_Tab_title}   10s
	Element Should Be Visible	${federation_Tab_title}
	Wait Until Element Is Visible    ${subscription_col}   10s							
	Element Should Be Visible	${subscription_col}
	Wait Until Element Is Visible    ${subscription_col_num}   10s
	Element Should Be Visible	${subscription_col_num}	
	
Verify view/add link in subscriptions column
    Wait Until Element Is Visible    ${view/add_link}   10s							
	Element Should Be Visible	${view/add_link}
	Click Element	${view/add_link}	
	
Verify view/add pop-up appears on click of view/add link	
 	sleep     5s							
	Wait Until Element Is Visible    ${subsciptions_id}   10s						
	Element Should Be Visible	${subsciptions_id}
	Wait Until Element Is Visible    ${catalog_name1}   10s							
	Element Should Be Visible	${catalog_name1}																														   
	Wait Until Element Is Visible    ${created_on}   10s							
	Element Should Be Visible	${created_on}																													   
	Wait Until Element Is Visible    ${frequency_of_update}   10s					
	Element Should Be Visible	${frequency_of_update}	
	Wait Until Element Is Visible    ${View/add_doneBtn}   10s							
	Element Should Be Visible	${View/add_doneBtn}	
	Click Element    ${View/add_doneBtn}
	
Verify delete icon is displaying on the error model(not in deleted section)
   Wait Until Element Is Visible    ${homeIcon}    10s
   Click Element    ${homeIcon}
   Wait Until Element Is Visible    ${myModelIcon}    10s
   Click Element    ${myModelIcon}
   Wait Until Element Is Visible    ${searchModelTxtbox}   30s
   Input Text    ${searchModelTxtbox}    ${SearchModelName_Error}
   sleep    10s
   Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${Delete_icon}     30s
   Element Should Be Visible    ${Delete_icon}

Verify error detail popup is open on click of error model
   Wait Until Element Is Visible    ${check_Image_loaded}     30s
   Click Element    ${Error_Foundlink}
   sleep    10s
   Wait Until Element Is Visible    ${Error_DetailsPopup}     30s
   Element Should Be Visible    ${Error_DetailsPopup}
   Wait Until Element Is Visible    ${closePoup_OK}     30s
   Element Should Be Visible    ${closePoup_OK}
   Click Element    ${closePoup_OK}

Verify delete is working for error model
   Wait Until Element Is Visible    ${Delete_icon}     30s
   Element Should Be Visible    ${Delete_icon}
   Click Element    ${Delete_icon}
   Wait Until Element Is Visible    ${Delete_ModelPopup}     30s
   Element Should Be Visible    ${Delete_ModelPopup}
   Wait Until Element Is Visible    ${Delete_ModelConfirmButton}     30s
   Click Element    ${Delete_ModelConfirmButton}	
	
Verify Search Functionality    
	 Wait Until Element Is Visible    ${homeIcon}    10s  
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s 
	 sleep    5s
	 Click Link        ${homeIcon}    
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
     Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   10  Element Text Should Be     ${imageToVerify}    ${SearchModelName_MyModel}   
	 sleep    5s
     
Verify filter by category functionality 
	 Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}    
	 Wait Until Element Is Visible    ${marketPlaceIcon}    30s
	 Click Element    ${marketPlaceIcon}
	 sleep    10s
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Wait until element is visible    ${filter_classification}    10s
	 Click Element     ${filter_classification}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Click Element     ${filter_classification}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Wait until element is visible    ${filter_DataSources}    10s
	 Click Element    ${filter_DataSources}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Click Element    ${filter_DataSources}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Wait until element is visible    ${filter_dataTransformer}    10s
	 Click Element     ${filter_dataTransformer}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Click Element     ${filter_dataTransformer}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Wait until element is visible    ${filter_prediction}    10s
	 Click Element     ${filter_prediction}
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
	 Click Element     ${filter_prediction}

Verify content on catalog screen
   Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s 
   Wait Until Element Is Visible    ${homeIcon}    10s 
   Click Link    ${homeIcon} 
   Wait Until Element Is Visible    ${catalogIcon}    10s
   Element Should Be Visible    ${catalogIcon}
   Click Element    ${catalogIcon}
   Wait Until Element Is Visible    ${catalogIconTitle}    10s
   Element Should Be Visible    ${catalogIconTitle} 
   Wait Until Element Is Visible    ${Catalog_Name}     10s
   Element Should Be Visible    ${Catalog_Name}
   Wait Until Element Is Visible    ${Publisher_Name}     10s
   Element Should Be Visible    ${Publisher_Name}
   Wait Until Element Is Visible    ${CreatedDate_Catalog}     10s
   Element Should Be Visible    ${CreatedDate_Catalog}
   Wait Until Element Is Visible    ${AccessType_Catalog}     10s
   Element Should Be Visible    ${AccessType_Catalog}
   Wait Until Element Is Visible    ${Total_Models}     10s
   Element Should Be Visible    ${Total_Models}
   Wait Until Element Is Visible    ${Action_Catalog}     10s
   Element Should Be Visible    ${Action_Catalog}
   Wait Until Element Is Visible    ${AddNew_Catalog}     10s
   Element Should Be Visible    ${AddNew_Catalog}
   Click Element	${AddNew_Catalog}
   Wait Until Element Is Visible    ${AddNew_Catalog_PopUp}     10s
   Element Should Be Visible    ${AddNew_Catalog_PopUp}
   Wait Until Element Is Visible    ${CatalogName_Text}     10s
   Element Should Be Visible    ${CatalogName_Text}
   Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
   sleep    5s
   Click Element	${CatalogName_Text}
   Input Text	${CatalogName_Text}		AUTOMATION_A
   Wait Until Element Is Visible    ${Accesslevel_Dropdown}     10s
   Element Should Be Visible    ${Accesslevel_Dropdown}
   Click Element	${Accesslevel_Dropdown}
   Wait Until Element Is Visible    ${Accesslevel_Public}     10s
   Element Should Be Visible    ${Accesslevel_Public}     
   Click Element	${Accesslevel_Public}     
   Wait Until Element Is Visible    ${AddDescription_Text}     10s
   Element Should Be Visible    ${AddDescription_Text}     
   Click Element	${AddDescription_Text}
   Input Text	${AddDescription_Text}	MY TEST MODELS NEW
   Wait Until Element Is Visible    ${Self_Publish}     10s
   # Click Element	${Self_Publish}
   Wait Until Element Is Enabled    ${AddCatalog_Button}     10s
   Click Element	${AddCatalog_Button}
   
Verify catalog detail is displaying when user selects a value from the drop down
    sleep    10s
    Wait Until Element Is Visible    ${searchCatalogTxtbox}   30s
    Wait Until Keyword Succeeds  60    5    Wait Until Element Is Not Visible    ${overlay}    10s
    sleep    5s
	Click Element    ${searchCatalogTxtbox}
	Input Text    ${searchCatalogTxtbox}    ${SearchCatalogName}
	Wait Until Element Is Visible    ${CatalogName_Link}    10s
	Element Should Be Visible    ${CatalogName_Link}
    Click Element    ${CatalogName_Link}
	Wait Until Element Is Visible    ${ViewCatalog_PopUp}    10s
	Element Should Be Visible    ${ViewCatalog_PopUp}
	Wait Until Element Is Visible    ${CatalogName_Name}    10s
	Element Should Be Visible    ${CatalogName_Name}
	Wait Until Element Is Visible    ${CatalogName_Link_OK}    10s
	Element Should Be Visible    ${CatalogName_Link_OK}
    Click Element    ${CatalogName_Link_OK}
    
Verify edit catalog functionality
   Wait Until Element Is Visible    ${EditCatalog}     30s
   Element Should Be Visible            ${EditCatalog}     
   Click Element	${EditCatalog}
   Wait Until Element Is Visible    ${CatalogName_Text}     30s
   Element Should Be Visible            ${CatalogName_Text}
   Clear Element Text	${CatalogName_Text}
   Input Text	${CatalogName_Text}		AUTOMATION_B
   Wait Until Element Is Visible    ${Accesslevel_Dropdown}     30s
   Element Should Be Visible            ${Accesslevel_Dropdown}
   Click Element	${Accesslevel_Dropdown}
   Wait Until Element Is Visible    ${Accesslevel_Public1}     30s
   sleep    10s
   Element Should Be Visible    ${Accesslevel_Public1}     
   Click Element	${Accesslevel_Public1} 
   sleep    10s    
   Wait Until Element Is Enabled    ${UpdateCatalog_Button}     30s
   Click Element	${UpdateCatalog_Button} 
   sleep    10s
   
Verify delete catalog functionality
   Click Element    ${searchCatalogTxtbox}
   Input Text    ${searchCatalogTxtbox}    "AUTOMATION_B"     
   Wait Until Element Is Visible    ${DeleteCatalog}     30s
   Element Should Be Visible    ${DeleteCatalog}     
   Click Element	${DeleteCatalog}
   Wait Until Element Is Visible    ${DeleteCatalog_Pop-up}     30s
   Element Should Be Visible    ${DeleteCatalog_Pop-up}
   Wait Until Element Is Visible    ${DeleteCatalog_Pop-up_Confirm}     30s
   Click Element	${DeleteCatalog_Pop-up_Confirm}  
   
Verify "Peer access" icon display under action section on catalog page
    Wait Until Element Is Visible    ${homeIcon}    10s
    Click Element    ${homeIcon}
	Wait Until Element Is Visible    ${catalogIcon}    10s
    Click Element    ${catalogIcon}
	Wait Until Element Is Visible    ${AddNew_Catalog}     10s
    Element Should Be Visible    ${AddNew_Catalog}
    Click Element	${AddNew_Catalog}
    Wait Until Element Is Visible    ${AddNew_Catalog_PopUp}     10s
    Element Should Be Visible    ${AddNew_Catalog_PopUp}
    Wait Until Element Is Visible    ${CatalogName_Text}     10s
    Element Should Be Visible    ${CatalogName_Text}
    Click Element	${CatalogName_Text}
    Input Text	${CatalogName_Text}		Restricted_Catalog_Automation
	Wait Until Element Is Visible    ${Accesslevel_Dropdown}     10s
    Element Should Be Visible    ${Accesslevel_Dropdown}
    Click Element	${Accesslevel_Dropdown}
    Wait Until Element Is Visible    ${Accesslevel_Restricted}     10s
    Element Should Be Visible    ${Accesslevel_Restricted}     
    Click Element	${Accesslevel_Restricted}     
    Wait Until Element Is Visible    ${AddDescription_Text}     10s
    Element Should Be Visible    ${AddDescription_Text}     
    Click Element	${AddDescription_Text}
    Input Text	${AddDescription_Text}	Testing
	Wait Until Element Is Enabled    ${AddCatalog_Button}     10s
    Click Element	${AddCatalog_Button}
    sleep    10s
	Input Text	${searchCatalogTxtbox}    "Restricted_Catalog_Automation"
	Wait Until Element Is Visible    ${ManagePeer}    10s
	Element Should Be Visible	${ManagePeer} 
	
Verify "Grant peer access" button display on manage peer(s)Access page
	Click Element	${ManagePeer}
	Wait Until Element Is Visible    ${GrantPeerAccess}    5s
	# Element Should Be Visible	${GrantPeerAccess}         

Verify that user will click on (X) icon or cancel button from grant peer access pop-up
    sleep    5s
	Click Element	${GrantPeerAccess}
	# Wait Until Element Is Visible	${GrantPeerAccess_Popup}	10s
	Wait Until Element Is Visible	${Cancel_PeerAccess}	5s
	Click Element	${Cancel_PeerAccess}

Verify that user will click on "Grant Access" button from grant peer access pop-up without selecting any peer
    Click Element	${GrantPeerAccess}
	Wait Until Element Is Visible	${GrantPeerAccess_Popup}	2s
	Wait Until Element Is Visible	${Peer_Name}	2s
	Wait Until Element Is Visible	${FDQN}    2s
	Wait Until Element Is Visible	${Email_Peer}	2s
	
Verify that user will click on "Grant Access" button from grant peer access pop-up
	Wait Until Element Is Visible	 ${Checkbox_peerAccess}    2s
	Click Element	${Checkbox_peerAccess}
	# Wait Until Element Is Enabled	${Grant_Access}		10s
	Click Element	${Grant_Access}
	
Verify that user will click on "Remove button" from manage peer(s) access page
	Wait Until Element Is Visible	 ${Checkbox_1}    2s
	Click Element	${Checkbox_1}
	# Wait Until Element Is Visible    ${GrantPeer_RemoveBtn}    10s
	Click Element	${GrantPeer_RemoveBtn}
	# Wait Until Element Is Visible	 ${Remove_Confirmation}    10s
	Click Element	${Remove_Confirmation}	

Verify that user will click on (X) icon from manage peer(s) access page
    Click Element	${GrantPeerAccess}
	Wait Until Element Is Visible	 ${Checkbox_peerAccess}    5s
	Click Element	${Checkbox_peerAccess}
	# Wait Until Element Is Enabled	${Grant_Access}		10s
	Click Element	${Grant_Access}
	Wait Until Element Is Visible	 ${Action_1}    5s
	Click Element	${Action_1}
	# Wait Until Element Is Visible	 ${Confirmation_popup}    10s
	Click Element	${Confirm_Remove} 

Verify error message is displaying when no author is added and user tries to publish the model
    Wait Until Element Is Visible    ${homeIcon}    10s    
    Click Link	${homeIcon}
    Wait Until Element Is Visible    ${myModelIcon}    10s
    Click Element    ${myModelIcon}
    Wait Until Element Is Visible    ${searchModelTxtbox}   30s
      # Click Element    ${searchModelTxtbox}
    Input Text    ${searchModelTxtbox}    ${SearchModelName_Unpublish}
    Wait Until Keyword Succeeds    60   10  Element Text Should Be    ${imageToUnPublish}    ${SearchModelName_Unpublish}    
	Wait Until Element Is Visible    ${check_Image_loaded_UN}    30s			
	sleep   10s
	Click Element	${check_Image_loaded_UN}
	Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	Click Element       ${manageMyModelBtn}
	sleep    10s
	Wait Until Element Is Visible    ${publishToMarketplaceTab}    30s    
	Click Element    ${publishToMarketplaceTab}
	sleep   15s
	Wait Until Element Is Visible    ${Add_Author_Error}	10s									
    Element Should Be Visible    ${Add_Author_Error}
	
Verify Model Details page Tabs 
     sleep    10s   
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 sleep    10s 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Click Element    ${searchModelTxtbox}
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   5  Element Text Should Be     ${imageToVerify}     ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60   5    Wait Until Element Is Visible    ${check_Image_loaded}     30s
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${descriptionTab}    10s
	 Element Should Be Visible   ${descriptionTab}
	 Wait Until Element Is Visible    ${LicenseTab}    10s
	 Element Should Be Visible   ${LicenseTab}   
	 Wait Until Element Is Visible    ${signaturesTab}    10s
	 Element Should Be Visible    ${signaturesTab}    
	 Wait Until Element Is Visible    ${documentsTab}    10s
	 Element Should Be Visible    ${documentsTab}    
	 Wait Until Element Is Visible    ${modelArtifactTab}    10s    
	 Element Should Be Visible    ${modelArtifactTab} 
	 Wait Until Element Is Visible    ${Author/publisherDetailsTab}    10s    
	 Element Should Be Visible    ${Author/publisherDetailsTab}

Verify Solution ID is displaying on Model Details page 
     Wait Until Keyword Succeeds  60   5    Wait Until Element Is Visible    ${myModelIcon}    10s
	  Click Element    ${myModelIcon} 
	  Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	  Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	  Wait Until Keyword Succeeds  60    5    Element Text Should Be     ${imageToVerify}     ${SearchModelName_MyModel}
	  Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${check_Image_loaded}
	  Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    30s
	  Click Element    ${check_Image_loaded}
	  sleep    10s
	  Wait Until Element Is Visible    ${solutionID_ModelDetails}    10s
	  Element Should Be Visible   ${solutionID_ModelDetails}
	  
Verify Solution ID is displaying on Manage My Model Page
     sleep    10s
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    15s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${solutionID_MyModels}    20s
	 Element Should Be Visible    ${solutionID_MyModels}    	 

Verify Delete Model In MyModels For Unpublished Model
     Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}                            
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${DeleteModelName}
	 Wait Until Keyword Succeeds  60   10  Element Text Should Be     ${imageToDelete}    ${DeleteModelName} 
	 sleep    10s 
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${DeleteModelTab}    30s    
	 Click Element     ${DeleteModelTab}
	 Wait Until Element Is Visible    ${DeleteButton_MyModels}    10s
	 Click Element    ${DeleteButton_MyModels}
	 Wait Until Element Is Visible    ${DeleteButton_Confirm_Popup}    10s
	 Wait Until Element Is Visible    ${DeleteButton_Confirm}    10s
	 sleep    10s
	 Click Element    ${DeleteButton_Confirm}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s 
     sleep    10s
	 Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}                            
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${DeleteModelName}
	 Wait Until Keyword Succeeds  60   5  Element Text Should Be     ${DeletedModel_InMyModels}    ${DeleteModelName}     
	  
Verify the Status of Unpublished solution in Model details page
     Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60    5    Element Text Should Be     ${imageToVerify}     ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60    5     Wait Until Element Is Visible    ${check_Image_loaded}     20s    
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${status_Unpublished}    10s
	 Element Should Be Visible    ${status_Unpublished}        

Verify dashboard options in Site Admin   
	 Wait Until Element Is Visible    ${siteAdminIcon}    10s
	 Click Element    ${siteAdminIcon}
	 Wait Until Element Is Visible    ${monitoring_tab}    10s
	 Element Should Be Visible   ${monitoring_tab}
	 Click Element    ${monitoring_tab}  
	 Wait Until Element Is Visible    ${roleMgmtTab}    10s
	 Element Should Be Visible    ${roleMgmtTab} 
	 Click Element    ${roleMgmtTab} 
	 Wait Until Element Is Visible    ${user_Management_Tab}    10s
	 Element Should Be Visible    ${user_Management_Tab} 
	 Click Element    ${user_Management_Tab}
	 Wait Until Element Is Visible    ${SiteContent_Tab}    10s
	 Element Should Be Visible    ${SiteContent_Tab}  
	 Click Element    ${SiteContent_Tab} 
	 Wait Until Element Is Visible    ${site_Configuration_Tab}    10s
	 Element Should Be Visible    ${site_Configuration_Tab} 
	 Click Element    ${site_Configuration_Tab}
	 Wait Until Element Is Visible    ${MaintainedBackupLogs}    10s
	 Element Should Be Visible    ${MaintainedBackupLogs} 
	 Click Element    ${MaintainedBackupLogs}
     Wait Until Element Is Visible    ${federation_Tab}    10s
	 Element Should Be Visible    ${federation_Tab}
	 Click Element    ${federation_Tab}    

Verify the Status of Deleted solution in Model details page
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}    10s
	 Input Text    ${searchModelTxtbox}    ${DeleteModelName}
	 Wait Until Keyword Succeeds  60   10  Element Text Should Be     ${DeletedModel_InMyModels}    ${DeleteModelName}
	 sleep    5s
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Visible    ${check_Image_loaded_DELa}    20s
	 Wait Until Element Is Visible    ${check_Image_loaded_DELa}
	 Click Element    ${check_Image_loaded_DELa}
	 Wait Until Element Is Visible    ${status_Deleted}    10s
	 Element Should Be Visible    ${status_Deleted} 

Verify that Manage My Model Button for Deleted solution is disabled
     Wait Until Element Is Visible    ${manageMyModel_Btn_ForDeletedModel}    10s
	 Element Should Be Visible    ${manageMyModel_Btn_ForDeletedModel}

Verify unpublish tab is present for published models
    Wait Until Element Is Visible    ${homeIcon}    10s    
     Click Link	${homeIcon}
     Wait Until Element Is Visible    ${myModelIcon}    10s
     Click Element    ${myModelIcon}
     Wait Until Element Is Visible    ${searchModelTxtbox}   30s
     Input Text    ${searchModelTxtbox}    ${SearchModelName_Unpublish}
     Wait Until Keyword Succeeds    60   10  Element Text Should Be    ${imageToUnPublish}    ${SearchModelName_Unpublish}    
	  Wait Until Element Is Visible    ${check_Image_loaded_UN}    30s			
	  sleep   10s
	  Click Element	${check_Image_loaded_UN}
	  Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	  Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	  Click Element       ${manageMyModelBtn}
	  sleep    10s
	 Wait Until Element Is Visible    ${manageAuthors}    20s
	 Element Should Be Visible     ${manageAuthors}
	 Click Element    ${manageAuthors}
     Wait Until Element Is Visible    ${publisherName_Authors}    10s
	 Input Text    ${publisherName_Authors}     Automation 
	 Wait Until Element Is Enabled    ${SaveBtn}    15s
	 Element Should Be Enabled    ${SaveBtn}
	 Click Element    ${SaveBtn}   
	 Wait Until Element Is Visible    ${authorName}    10s
	 Input Text    ${authorName}     Root
	 Input Text    ${authorContactInfo}    Root@123
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Wait Until Element Is Enabled    ${addAuthorBtn}    15s
	 Element Should Be Enabled    ${addAuthorBtn}    
	 Click Element    ${addAuthorBtn}
	 sleep    20s
	  Wait Until Element Is Visible    ${publishToMarketplaceTab}    30s    
	  Click Element    ${publishToMarketplaceTab}
	  sleep   15s
	  Wait Until Element Is Visible    ${selectCatalog}    10s
     Element Should Be Visible    ${selectCatalog}
     Wait Until Element Is Visible    ${selectCatalog_Dropdown}    10s
     Element Should Be Visible    ${selectCatalog_Dropdown}
     sleep    5s
     Click Element    ${selectCatalog_Dropdown}
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${Catalog_Ist_TEST}	10s
	 Element Should Be Visible    ${Catalog_Ist_TEST}
	 Click Element    ${Catalog_Ist_TEST}
      # Wait Until Element Is Visible    ${stepstoSubmit}	10s
      # Element Should Be Visible    ${stepstoSubmit}
     Wait Until Element Is Visible    ${ModelName_Completed}	10s
     Element Should Be Visible    ${ModelName_Completed}
	  ${status_modelDescPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${modelDescription_Completed_Public}
	  Run Keyword If    "${status_modelDescPub}" == "FAIL"    Wait Until Element Is Visible     ${modelDescription_NotCompleted_Public}     15s
	  Run Keyword If      "${status_modelDescPub}" == "FAIL"    Click Element    ${modelDescriptionBtn_Public}
	  Run Keyword If      "${status_modelDescPub}" == "FAIL"    Input Text    ${modelDescription_text_Public}    Test Desc
	  Clear Element Text    ${modelDescription_text_Public}
	  Run Keyword If      "${status_modelDescPub}" == "FAIL"    Input Text    ${modelDescription_text_Public}    Test Desc
	  Run Keyword If      "${status_modelDescPub}" == "FAIL"    Wait Until Element Is Enabled    ${ModelDescription_DoneBtn_Public}    60s
	  Element Should Be Enabled    ${ModelDescription_DoneBtn_Public}   
      Click Element    ${ModelDescription_DoneBtn_Public}
      Wait Until Element Is Visible    ${Ok_Button}    10s
      Click Element    ${Ok_Button}
	  Wait Until Element Is Visible     ${modelDescription_Completed_Public}     15s
	  ${status_modelCategoryPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${ModelCategory_Completed_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Wait Until Element Is Visible    ${ModelCategoryBtn_Public}     10s
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Click Element    ${ModelCategoryBtn_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Execute JavaScript    window.scrollTo(0,100)
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectCategoryDrpdwn_Public}    10s
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectCategoryDrpdwn_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectModelCategory_PR_Public}    10s 
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectModelCategory_PR_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectToolkitTypeDrpdwn_Public}   5s
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element     ${SelectToolkitTypeDrpdwn_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectToolkitType_H2O_Public}    10s 
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectToolkitType_H2O_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Enabled    ${ModelCategory_Done_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${ModelCategory_Done_Public}
	  Run Keyword If      "${status_modelCategoryPub}" == "FAIL"     Wait Until Element Is Visible     ${ModelCategory_Completed_Public}    15s
	  # Wait Until Element Is Visible    ${Ok_Button}    10s
      # Click Element    ${Ok_Button}
	  Click Element    ${SkipModelDocumentsCheckbox_Public}
	  Click Element    ${SkipModel_DoneBtn_Public}
	  ${status_TagPresentPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${ModelTag_Completed_Public}
	  Run Keyword If      "${status_TagPresentPub}" == "FAIL"   Wait Until Element Is Visible     ${ModelTagsBtn_public}    10s
	  Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Wait Until Element Is Visible    ${ModelTagsBtn_public_Input}   
	  Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Input Text   ${ModelTagsBtn_public_Input}   TestingMarketplaceTag
	  Press Key    ${ModelTagsBtn_public_Input}  \\13
	  sleep  5s
	  Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Click Element    ${ModelTagsBtn_public}
	  Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Wait Until Element Is Visible    ${ModelTag_Completed_Public}    15s
	  ${status_ImageUploadedPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${UploadImage_Completed_Public}
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Not Visible    ${overlay}    10s
     Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    sleep  5s
     Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element    ${UploadImageForModelBtn_Public}
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Visible    ${UploadIcon_Java_Png_Public}     10s
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element    ${UploadIcon_Java_Png_Public}
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    sleep  5s
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element     ${UploadIcon_Done_Public}
	  Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Visible    ${UploadImage_Completed_Public}    15s  
	  Wait Until Element Is Enabled    ${submitToPublicationBtn_Public}         10s	  
	  Click Element    ${submitToPublicationBtn_Public}
	  Wait Until Element Is Visible    ${Model_Publish_Confirm}	10s
     Element Should Be Visible    ${Model_Publish_Confirm}
     Wait Until Element Is Visible    ${Model_Publish_Confirm_OK}	10s
     Click Element    ${Model_Publish_Confirm_OK}
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${WithdrawRequestBtn_Public}    40s
     sleep    5s
	  Click Element    ${PublishRequestIcon}
	  Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	  sleep    5s
	  Wait Until Element Is Visible    ${search_PublishRequest}    10s
	  Input Text    ${search_PublishRequest}    ${SearchModelName_Unpublish}
	  Wait Until Keyword Succeeds  60   10    Wait Until Element Contains    ${searchedModelNameForApproval}    ${SearchModelName_Unpublish}    30s
	  sleep    5s
	  Click Element    ${approve_PublishRequest}
	  Wait Until Element Is Visible    ${Approverequest_popup}    10s
	  Input Text   ${Approverequest_Text}    Approved
	  Wait Until Element Is Visible    ${approveBtn}    10s
     Wait Until Element Is Enabled    ${approveBtn}    10s
	  Click Element    ${approveBtn}
     Wait Until Keyword Succeeds    45    5    Wait Until Element Is Visible    ${requestorStatus}
     Wait Until Keyword Succeeds    45    5    Element Should Contain    ${requestorStatus}    Approved  
	  sleep	10s
	 Wait Until Keyword Succeeds    60   10    Wait Until Element Is Visible    ${marketPlaceIcon}    10s
	 sleep    5S
	 Element Should Be Visible    ${marketPlaceIcon}
     Click Element    ${marketPlaceIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
      # Click Element    ${searchModelTxtbox}
     Input Text    ${searchModelTxtbox}    ${SearchModelName_Unpublish}
     Wait Until Keyword Succeeds    60   10  Element Text Should Be    ${imageToUnPublishA}    ${SearchModelName_Unpublish}    
	 Wait Until Element Is Visible    ${check_Image_loaded_UN}    30s			
	 sleep   10s
	 Click Element	${check_Image_loaded_UN}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${publishToMarketplaceTab}    30s    
	 Click Element    ${publishToMarketplaceTab}
	 sleep   15s
	 Wait Until Element Is Visible    ${selectCatalog_publishedModel}	10s
     Element Should Be Visible    ${selectCatalog_publishedModel}
     Wait Until Element Is Visible    ${selectCatalog_publishedModel_dropdown}	10s
     Element Should Be Visible    ${selectCatalog_publishedModel_dropdown}
     Wait Until Keyword Succeeds    60   10    Click Element    ${selectCatalog_publishedModel_dropdown}
     Wait Until Element Is Visible    ${Catalog_Ist_TEST_A}	10s
	 Element Should Be Visible    ${Catalog_Ist_TEST_A}
     Click Element    ${Catalog_Ist_TEST_A}
	 sleep	5s
	 Wait Until Element Is Enabled	${UnpublishButton}	15s
	 Element Should Be Enabled	${UnpublishButton}

Verify the unpublish model functionality
    Wait Until ELement Is Visible	${UnpublishButton}    10s
    Element Should Be Visible	${UnpublishButton}
    Click Element	${UnpublishButton}	
    
Verify that the unpublish model pop-up should be visible after clicking unpublish model button on manage my models page
     sleep	5s
     Wait Until Element Is Visible	${UnpublishButton_PopUp}	10s
     Element Should Be Visible	${UnpublishButton_PopUp}
     Wait Until Element Is Visible	${UnpublishButton_Confirm}	10s
     Element Should Be Visible	${UnpublishButton_Confirm}
     Click Element    ${UnpublishButton_Confirm}    
     sleep    5s
     Wait Until Element Is Visible    ${homeIcon}    10s    
     Click Link	${homeIcon}
     Wait Until Element Is Visible    ${myModelIcon}    10s
     Click Element    ${myModelIcon}
     Wait Until Element Is Visible    ${searchModelTxtbox}   30s
     Click Element    ${searchModelTxtbox}
     Input Text    ${searchModelTxtbox}    ${SearchModelName_Unpublish}
     Wait Until Keyword Succeeds    60   10  Element Text Should Be    ${imageToUnPublish}    ${SearchModelName_Unpublish}    
	 Wait Until Element Is Visible    ${check_Image_loaded_UN}    30s			
	 sleep   10s
	 Click Element	${check_Image_loaded_UN}
	 Wait Until Element Is Visible    ${status_Unpublished}    10s
	 Element Should Be Visible    ${status_Unpublished}      

Verify unpublish tab is not present for unpublished models
     Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60    5    Element Text Should Be     ${imageToVerify}     ${SearchModelName_MyModel}
	 Wait Until Keyword Succeeds  60    5     Wait Until Element Is Visible    ${check_Image_loaded}     20s    
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${publishToMarketplaceTab}    30s    
	 Click Element    ${publishToMarketplaceTab}
	 sleep   15s
	 Wait Until Element Is Visible	${UnpublishButton}
	 Element Should Be Disabled	${UnpublishButton}

Verify To Publish Solution In Marketplace    
   Wait Until Element Is Visible    ${homeIcon}    30s 
   Element Should Be Visible    ${homeIcon}
   Click Link    ${homeIcon}
   Wait Until Element Is Visible    ${catalogIcon}    10s
   Element Should Be Visible    ${catalogIcon}
   Click Element    ${catalogIcon}
   Wait Until Element Is Visible    ${catalogIconTitle}    10s
   Element Should Be Visible    ${catalogIconTitle} 
   Wait Until Element Is Visible    ${AddNew_Catalog}     10s
   Element Should Be Visible    ${AddNew_Catalog}
   Click Element	${AddNew_Catalog}
   Wait Until Element Is Visible    ${AddNew_Catalog_PopUp}     10s
   Element Should Be Visible    ${AddNew_Catalog_PopUp}
   Wait Until Element Is Visible    ${CatalogName_Text}     10s
   Element Should Be Visible    ${CatalogName_Text}
   Click Element	${CatalogName_Text}
   Input Text	${CatalogName_Text}		CATALOG_IST_TESTING
   Wait Until Element Is Visible    ${Accesslevel_Dropdown}     10s
   Element Should Be Visible    ${Accesslevel_Dropdown}
   Click Element	${Accesslevel_Dropdown}
   Wait Until Element Is Visible    ${Accesslevel_Public}     10s
   Element Should Be Visible    ${Accesslevel_Public}     
   Click Element	${Accesslevel_Public}     
   Wait Until Element Is Visible    ${AddDescription_Text}     10s
   Element Should Be Visible    ${AddDescription_Text}     
   Click Element	${AddDescription_Text}
   Input Text	${AddDescription_Text}	MY TEST MODELS
   # Wait Until Element Is Visible    ${Self_Publish}     10s
   # Click Element	${Self_Publish}
   Wait Until Element Is Enabled    ${AddCatalog_Button}     10s
   Click Element	${AddCatalog_Button}
   sleep    10s
   
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Click Element    ${searchModelTxtbox}
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_Public}
	 Wait Until Keyword Succeeds    60   10  Element Text Should Be    ${imageToPublish_Public}    ${SearchModelName_Public}    
	 Wait Until Element Is Visible    ${check_Image_loaded}    30s
	 sleep   10s
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    30s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    30s
	 Click Element       ${manageMyModelBtn}
	 sleep    10s
	 Wait Until Element Is Visible    ${manageAuthors}    20s
	 Element Should Be Visible     ${manageAuthors}
	 Click Element    ${manageAuthors}
     Wait Until Element Is Visible    ${publisherName_Authors}    10s
	 Input Text    ${publisherName_Authors}     Admin 
	 Wait Until Element Is Enabled    ${SaveBtn}    15s
	 Element Should Be Enabled    ${SaveBtn}
	 Click Element    ${SaveBtn}   
	 Wait Until Element Is Visible    ${authorName}    10s
	 Input Text    ${authorName}     Testing
	 Input Text    ${authorContactInfo}    Testing
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Wait Until Element Is Enabled    ${addAuthorBtn}    15s
	 Element Should Be Enabled    ${addAuthorBtn}    
	 Click Element    ${addAuthorBtn}
	 sleep    20s
	 Wait Until Element Is Visible    ${publishToMarketplaceTab}    30s    
	 Click Element    ${publishToMarketplaceTab}
	 sleep   15s
	 Wait Until Element Is Visible    ${selectCatalog}	10s
     Element Should Be Visible    ${selectCatalog}
     Wait Until Element Is Visible    ${selectCatalog_Dropdown}	10s
     Element Should Be Visible    ${selectCatalog_Dropdown}
     sleep    5s
     Click Element    ${selectCatalog_Dropdown}
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${Catalog_Ist_TEST}	10s
	 Element Should Be Visible    ${Catalog_Ist_TEST}
	 Click Element    ${Catalog_Ist_TEST}
     ${status_modelDescPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${modelDescription_Completed_Public}
	 Run Keyword If    "${status_modelDescPub}" == "FAIL"    Wait Until Element Is Visible     ${modelDescription_NotCompleted_Public}     15s
	 Run Keyword If      "${status_modelDescPub}" == "FAIL"    Click Element    ${modelDescriptionBtn_Public}
	 Run Keyword If      "${status_modelDescPub}" == "FAIL"    Input Text    ${modelDescription_text_Public}    Test Desc
	 Clear Element Text    ${modelDescription_text_Public}
	 Run Keyword If      "${status_modelDescPub}" == "FAIL"    Input Text    ${modelDescription_text_Public}    Test Desc
	 Run Keyword If      "${status_modelDescPub}" == "FAIL"    Wait Until Element Is Enabled    ${ModelDescription_DoneBtn_Public}    60s
	 Element Should Be Enabled    ${ModelDescription_DoneBtn_Public}   
     Click Element    ${ModelDescription_DoneBtn_Public}
     Wait Until Element Is Visible    ${Ok_Button}    10s
     Click Element    ${Ok_Button}
	 Wait Until Element Is Visible     ${modelDescription_Completed_Public}     15s
	 ${status_modelCategoryPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${ModelCategory_Completed_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Wait Until Element Is Visible    ${ModelCategoryBtn_Public}     10s
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Click Element    ${ModelCategoryBtn_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"    Execute JavaScript    window.scrollTo(0,100)
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectCategoryDrpdwn_Public}    10s
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectCategoryDrpdwn_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectModelCategory_PR_Public}    10s 
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectModelCategory_PR_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectToolkitTypeDrpdwn_Public}   5s
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element     ${SelectToolkitTypeDrpdwn_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Visible    ${SelectToolkitType_H2O_Public}    10s 
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${SelectToolkitType_H2O_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Wait Until Element Is Enabled    ${ModelCategory_Done_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"   Click Element    ${ModelCategory_Done_Public}
	 Run Keyword If      "${status_modelCategoryPub}" == "FAIL"     Wait Until Element Is Visible     ${ModelCategory_Completed_Public}    15s
	  # Wait Until Element Is Visible    ${Ok_Button}    10s
     # Click Element    ${Ok_Button}
	 Click Element    ${SkipModelDocumentsCheckbox_Public}
	 Click Element    ${SkipModel_DoneBtn_Public}
	 ${status_TagPresentPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${ModelTag_Completed_Public}
	 Run Keyword If      "${status_TagPresentPub}" == "FAIL"   Wait Until Element Is Visible     ${ModelTagsBtn_public}    10s
	 Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Click Element    ${ModelTagsBtn_public_Input}   
	 Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Input Text   ${ModelTagsBtn_public_Input}   TestingMarketplaceTag
	 Press Key    ${ModelTagsBtn_public_Input}  \\13
	 sleep  5s
	 Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Click Element    ${ModelTagsBtn_public}
	 Run Keyword If      "${status_TagPresentPub}" == "FAIL"  Wait Until Element Is Visible    ${ModelTag_Completed_Public}    15s
	 ${status_ImageUploadedPub}  ${result}=    Run keyword and ignore error    Element Should Not Be Visible    ${UploadImage_Completed_Public}
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Not Visible    ${overlay}    10s
     Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    sleep  5s
     Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element    ${UploadImageForModelBtn_Public}
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Visible    ${UploadIcon_Java_Png_Public}     10s
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element    ${UploadIcon_Java_Png_Public}
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    sleep  5s
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Click Element     ${UploadIcon_Done_Public}
	 Run Keyword If      "${status_ImageUploadedPub}" == "PASS"    Wait Until Element Is Visible    ${UploadImage_Completed_Public}    15s  
	   
	
     # Execute JavaScript    window.scrollTo(0,100)
     Wait Until Element Is Enabled    ${submitToPublicationBtn_Public}         10s	  
	 Click Element    ${submitToPublicationBtn_Public}
	 Wait Until Element Is Visible    ${Model_Publish_Confirm}	10s
     Element Should Be Visible    ${Model_Publish_Confirm}
     Wait Until Element Is Visible    ${Model_Publish_Confirm_OK}	10s
     Click Element    ${Model_Publish_Confirm_OK}
     Wait Until Element Is Visible    ${WithdrawRequestBtn_Public}    20s
     sleep    5s
	 Click Element    ${PublishRequestIcon}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Wait Until Element Is Visible    ${search_PublishRequest}    10s
	 Input Text    ${search_PublishRequest}    ${SearchModelName_Public}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Contains    ${searchedModelNameForApproval}    ${SearchModelName_Public}    30s
	 sleep    5s
	 Click Element    ${approve_PublishRequest}
	 Wait Until Element Is Visible    ${Approverequest_popup}    10s
	 Input Text   ${Approverequest_Text}    Approved
	 Wait Until Element Is Visible    ${approveBtn}    10s
     Wait Until Element Is Enabled    ${approveBtn}    10s
	 Click Element    ${approveBtn}
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${requestorStatus}    20s  
     Element Should Contain    ${requestorStatus}    Approved   
     
Verify catalog name is displaying on the tiles
    Wait Until Element Is Visible    ${marketPlaceIcon}    10s
	Element Should Be Visible    ${marketPlaceIcon}
    Click Element    ${marketPlaceIcon}
	Wait Until Element Is Visible    ${searchModelTxtbox}   30s
    Input Text    ${searchModelTxtbox}    ${SearchModelName_Public}
    Wait Until Keyword Succeeds    60    10    Element Text Should Be    ${imageToVerify_P}    ${SearchModelName_Public}
    Wait Until Element Is Visible    ${check_Image_loaded}     30s
    Element Should Be Visible    ${check_Image_loaded}
    Wait Until Element Is Visible    ${Catalog_Tile}     30s
    Element Should Be Visible    ${Catalog_Tile}  
      
Verify The Published Solution In Published To Marketplace   
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Wait Until Element Is Visible    ${check_Image_loaded_PUB}     30s
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_Public} 
	 Wait Until Keyword Succeeds  60   5  Element Text Should Be     ${image_Published_Public}    ${SearchModelName_Public}       
  
Verify the description available in published in marketplace model     
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${check_Image_loaded_PUB}    30s    #changed
	 Click Element    ${check_Image_loaded_PUB}
	 Wait Until Element Is Visible    ${PublishedDescription_PB}    10s
	 Element Should Be Visible    ${PublishedDescription_PB}     

Verify long comment is displaying on click of view
     Wait Until Element Is Visible    ${homeIcon}    10s
     Click Element    ${homeIcon}
     Wait Until Element Is Visible    ${publishRequestIcon}    10s
     Click Element    ${publishRequestIcon}
     Wait Until Element Is Visible    ${publishRequestPageTitle}
     Element Should Be Visible    ${publishRequestPageTitle}
     Wait Until Element Is Visible    ${View_Link}    10s
	 Element Should Be Visible   ${View_Link}
	 Click Element    ${View_Link}
	 Wait Until Element Is Visible    ${PublisherComments_Popup}    10s
	 Element Should Be Visible   ${PublisherComments_Popup}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${Approved_Text}    15s
	 Element Should Be Visible   ${Approved_Text}
	 Wait Until Element Is Visible    ${Hide_Link}    10s
	 Element Should Be Visible   ${Hide_Link}
	 Click Element    ${Hide_Link}

Verify complete model name display in the rate section on model description screen
     Wait Until Element Is Visible    ${homeIcon}    10s
	 Click Link        ${homeIcon}
	 Wait Until Element Is Visible    ${marketPlaceIcon}    10s
	 Click Link        ${marketPlaceIcon}
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${SearchModelName_Public}
	 Wait Until Keyword Succeeds  60   5    Element Text Should Be     ${imageToVerify_P}    ${SearchModelName_Public}
	 Wait Until Keyword Succeeds  60   5    Wait Until Element Is Visible    ${check_Image_loaded_PUBa}     30s
	 Click Element    ${check_Image_loaded_PUBa}
	 Wait Until Element Is Visible    ${descriptionTab}    15s
	 Wait Until Element Is Enabled    ${descriptionTab}    15s
	 Click Element    ${descriptionTab}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${Rate_Section}
	 Element Should Be Visible    ${Rate_Section}	 

Verify signature is displaying on model description screen for composite solution
     Wait Until Element Is Visible    ${homeIcon}    10s
     Click Element    ${homeIcon}  
     Wait Until Element Is Visible    ${marketPlaceIcon}    10s
     Click Link	${marketPlaceIcon}
     Input Text    ${searchModelTxtbox}    ${SearchModelName_Public}
     Wait Until Keyword Succeeds  60   10    Element Text Should Be     ${imageToVerify_P}    ${SearchModelName_Public}
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${check_Image_loaded_PUBa}     10s
     Element Should Be Visible    ${check_Image_loaded_PUBa} 
     Click Element    ${check_Image_loaded_PUBa}
	 Wait Until Element Is Visible    ${signaturesTab}    10s
	 Element Should Be Visible   ${signaturesTab}
	 Click Element    ${signaturesTab}  
	 Wait Until Element Is Visible    ${signaturesTitle}    10s
	 Element Should Be Visible   ${signaturesTitle}  

Verify category is displaying for model except unpublished status
     Wait Until Element Is Visible    ${homeIcon}    10s
     Click Element    ${homeIcon}  
     Wait Until Element Is Visible    ${marketPlaceIcon}    10s
     Click Link	${marketPlaceIcon}
     Input Text    ${searchModelTxtbox}    ${SearchModelName_Public}
     Wait Until Keyword Succeeds  60    5    Element Text Should Be    ${imageToVerify_P}    ${SearchModelName_Public}       
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${check_Image_loaded_PUBa}    30s    #changed
	 Click Element    ${check_Image_loaded_PUBa}
	 Wait Until Element Is Visible    ${Category_link}    10s
     Element Should Be Visible    ${Category_link}    
     
Verify Delete Model In MyModels For Published Model 
     Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}                            
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${Published_DeleteModelName}
	 Wait Until Keyword Succeeds  60    10    Element Text Should Be     ${imageToDelete_Published}    ${Published_DeleteModelName} 
	 Wait Until Keyword Succeeds  60    5    Wait Until Element Is Visible    ${check_Image_loaded}    10s     
	 Click Element    ${check_Image_loaded}
	 Wait Until Element Is Visible    ${manageMyModelBtn}    20s
	 Wait Until Element Is Enabled    ${manageMyModelBtn}    10s
	 Click Element       ${manageMyModelBtn}
	 Wait Until Element Is Visible    ${DeleteModelTab}    30s    
	 Click Element     ${DeleteModelTab}
	 Wait Until Element Is Visible    ${DeleteButton_MyModels}    10s
	 Click Element    ${DeleteButton_MyModels}
	 Wait Until Element Is Visible    ${DeleteButton_Confirm_Popup}    10s
	 Wait Until Element Is Visible    ${DeleteButton_Confirm}    10s
	 Click Element    ${DeleteButton_Confirm}
	 Wait Until Element Is Visible    ${homeIcon}    10s    
	 Click Link        ${homeIcon}                            
	 Wait Until Element Is Visible    ${myModelIcon}    10s
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s
	 Click Element    ${myModelIcon} 
	 Wait Until Element Is Visible    ${searchModelTxtbox}   30s
	 Input Text    ${searchModelTxtbox}    ${Published_DeleteModelName}
	 Wait Until Keyword Succeeds  60   5  Element Text Should Be     ${DeletedModel_InMyModels}    ${Published_DeleteModelName}           	 	 

Verify whether role management tab is present in dashboard options
    Wait Until Element Is Visible    ${homeIcon}   30s
	Click Element    ${homeIcon}
	Wait Until Element Is Visible    ${siteAdminIcon}    10s
	Click Element    ${siteAdminIcon}
	Wait Until Element Is Visible    ${roleMgmtTab}    10s
	Element Should Be Visible	${roleMgmtTab}
	
Verify whether role management tab is clickable
	sleep	5s
	Click Element    ${roleMgmtTab}
	
Verify components in role management tab
	Wait Until Element Is Visible    ${roleMgmtTitle}    10s
	Element Should Be Visible	${roleMgmtTitle}
	Wait Until Element Is Visible    ${roleName}    10s
	Element Should Be Visible	${roleName}
	# Wait Until Element Is Visible    ${ModulePermission}    10s
	# Element Should Be Visible	${ModulePermission}
	Wait Until Element Is Visible    ${roleMgmtAction}    10s
	Element Should Be Visible	${roleMgmtAction}
	
Verify whether sorting is working for role management options
	Wait Until Element Is Visible    ${roleName}    10s
	Click Element	${roleNameSorting}
	# Wait Until Element Is Visible    ${ModulePermission}    10s
	# Click Element	${ModulePermissionSorting}

Verify whether create new role button is present in role management page
	Wait Until Element Is Visible    ${createNewRole}    10s
	Element Should Be Visible	${createNewRole}
	
Verify create new role functionality
	sleep	5s
	Click Element	${createNewRole}
	Wait Until Element Is Visible    ${createNewRole_Popup}    10s
	Click Element	${Role_Name_TextBox}
	Input Text	${Role_Name_TextBox}	Testing_Role
	Click Element	${select_Cat_Perm}	
	Wait Until Element Is Enabled	${createNewRole_Button}    10s
	Click Element	${createNewRole_Button}
	
Verify whether new role is visible in role management page after creating it
   	sleep	5s
	Click Element	${SearchByRole}
	Input Text	${SearchByRole}		Testing_Role
	Wait Until Element Is Visible    ${New_Role}    10s
	Element Should Be Visible	${New_Role}

Verify update role functionality
	Wait Until Element Is Visible    ${Edit_Role}    10s
	Click Element	${Edit_Role}
	Clear Element Text	${Role_Name_TextBox}
	Input Text	${Role_Name_TextBox}	Test_Roles
	Wait Until Element Is Enabled	${updateNewRole_Button}		10s
	Element Should Be Enabled	${updateNewRole_Button}
	Click Element	${updateNewRole_Button}
	
Verify delete role functionality
	sleep	5s
	Click Element	${SearchByRole}
	Input Text	${SearchByRole}		Test_Roles
	Wait Until Element Is Visible    ${Delete_Role}    10s
	Element Should Be Visible	${Delete_Role}
	Click Element	${Delete_Role}
	Wait Until Element Is Visible    ${Delete_Role_Popup}    10s
	Click Element	${Delete_Role_Confirm}
	sleep	2s
	Input Text	${SearchByRole}		Test_Roles
	Wait Until Element Is Visible    ${No_Results_Found}    10s
	
Verify adding new user in User Management and User Activation
     Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${homeIcon}    10s
     Click Link        ${homeIcon}
     Wait Until Element Is Visible    ${siteAdminIcon}         15s
     Click Element    ${siteAdminIcon}
     Wait Until Element Is Visible    ${user_Management_Tab}    15s
     Click Element    ${user_Management_Tab}
     Wait Until Element Is Visible    ${add_NewUser_Btn}
     Click Element    ${add_NewUser_Btn}
     ${addUser_Data} =   Get Current Date    result_format=%d_%m_%Y_%H_%M_%S
     Set Suite Variable    ${addUser_Data}
     Wait Until Element Is Visible    ${fname_AddUser}    10s
     Input Text    ${fname_AddUser}    ${addUser_Data}
     Wait Until Element Is Visible    ${lname_AddUser}    10s
     Input Text    ${lname_AddUser}    ${addUser_Data}
     Wait Until Element Is Visible    ${userName_AddUser}    10s
     Input Text    ${userName_AddUser}    ${addUser_Data}
     Wait Until Element Is Visible    ${email_AddUser}    10s
     Input Text    ${email_AddUser}    ${addUser_Data}@test.com
     Wait Until Element Is Visible    ${password_AddUser}    10s
     Input Text    ${password_AddUser}    Test@1234user
     Wait Until Element Is Visible    ${confirmPass_AddUser}     10s
     Input Text    ${confirmPass_AddUser}    Test@1234user
     Wait Until Element Is Visible    ${role_AddUser_DrpDwn}    10s
     Click Element    ${role_AddUser_DrpDwn}
     Wait Until Element Is Visible    ${select_MLP_SystemUser}     10s
     Click Element    ${select_MLP_SystemUser}
     Wait Until Element Is Visible    ${role_AddUser_DrpDwnA}    10s
     Log Source 
     Set Focus To Element    ${role_AddUser_DrpDwnA}
     Click Element    ${role_AddUser_DrpDwnA}
     Wait Until Element Is Enabled      ${addBtn_AddUser}    10s
     Click Element    ${addBtn_AddUser}
     Wait Until Element Is Visible    ${searchUser_UserManagement}    15s
     Input Text    ${searchUser_UserManagement}    ${addUser_Data}@test.com
     Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_uname}    ${addUser_Data}
     Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_email}    ${addUser_Data}@test.com
     Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_role_MLPSysUser}    MLP System User
     Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_status}    Pending
     Click Element    ${AddedUser_FirstChkBox}
     Click Element    ${bulkActionsDrpDwn}
     Wait Until Element Is Visible    ${bulkAction_ActiveUserOption}    5s
     Click Element    ${bulkAction_ActiveUserOption}
     Click Element    ${UserMgmt_ApplyBtn}
     Wait Until Element Is Visible    ${confirmBtn_ActiveUserPopup}    15s
     Click Element    ${confirmBtn_ActiveUserPopup}
     Wait Until Keyword Succeeds  45   5  Element Text Should Be    ${registeredAddUser_status}    Active
	  
Verify Logout            
	 Wait Until Element Is Visible    ${signOut}      10s
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Not Visible    ${overlay}    10s
	 sleep    5s 
	 Element Should Be Visible    ${signOut}       
	 Click Element        ${signOut}    
	 Wait Until Keyword Succeeds     60     5    Wait Until Element Is Visible    ${signInLink}   30s
	 Wait Until Keyword Succeeds     60     5    Element Should Be Visible    ${signInLink}    30s    #CHANGED
           
Verify Add User By Login With Newly Added User
	  # Open Browser    ${URL}   ${BROWSER}       ff_profile_dir=${FF_PROFILE}
	  # sleep  3s
	 ${addedUser}=     Get Variable Value           ${addUser_Data}
	 Set Suite Variable    ${addedUser}              
	 Wait Until Keyword Succeeds  60    10    Wait Until Element Is Visible    ${signInLink}    30s
	 sleep    10s
	 Element Should Be Visible    ${signInLink}
	 Click Element        ${signInLink}
	  #sleep  15s
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   25s   
	 Input Text    ${loginEmailAddressEntry}      ${addedUser} 
	  #sleep  15s 
	 Wait Until Element Is Visible    ${loginPassword}    25s
	 Input Text    ${loginPassword}    Test@1234user
	 Click Button    ${signInButton}
	 Wait Until Keyword Succeeds  60   10    Wait Until Element Is Visible    ${loginAccountInfo}    60s
	 Element Should Be Visible    ${loginAccountInfo}  
	  #Close Browser
      
Verify Change Password On Account Setting Page
	 ${status_interestPopup}  ${result}=    Run keyword and ignore error    Wait Until Element Is Visible      ${interestPopup_closeBtn}    30s
	 Sleep    3s
	 Run Keyword If      "${status_interestPopup}" == "PASS"     Click Element    ${interestPopup_closeBtn}    
	 ${CP_User}=     Get Variable Value           ${addedUser}
	 Wait Until Element Is Visible    ${accountInfo_Dropdown}    30s
	 sleep    15s
	 Element Should Be Visible    ${accountInfo_Dropdown}
	 sleep    5s
	 Click Element    ${accountInfo_Dropdown}
	 Wait Until Element Is Visible    ${accountSetting_link}    30s
	 Click Link    ${accountSetting_link}
	 Wait Until Element Is Visible    ${changePasswordLink}    30s
	 Click Element    ${changePasswordLink}
	 Wait Until Element Is Visible    ${CP_OldPassword}    30s
	 Input Text    ${CP_OldPassword}    Test@1234user
	 Wait Until Element Is Visible    ${CP_NewPassword}    30s
	 Input Text    ${CP_NewPassword}    NewSignUPTest@123
	 Wait Until Element Is Visible    ${CP_ConfirmPassword}    30s
	 Input Text    ${CP_ConfirmPassword}    NewSignUPTest@123
	 Wait Until Element Is Enabled    ${CP_ConfirmBtn}    25s
	 Click Element    ${CP_ConfirmBtn}
	 Wait Until Keyword Succeeds  45   5    Wait Until Element Is Visible    ${signInLink}    30s
	 Click link        ${signInLink}
	 Wait Until Element Is Visible    ${loginEmailAddressEntry}   25s
	 Input Text    ${loginEmailAddressEntry}      ${CP_User} 
	 Wait Until Element Is Visible    ${loginPassword}    25s
	 Input Text    ${loginPassword}    NewSignUPTest@123
	 Wait Until Element Is Visible    ${signInButton}    30s
	 Click Button    ${signInButton}
	 Wait Until Element Is Visible    ${loginAccountInfo}    25s
	 Element Should Be Visible    ${loginAccountInfo}
	 Close Browser    
     
Tear Down   #Close all browsers
	 [Documentation]   Close all browsers 
	 Close All Browsers

